import { config } from 'dotenv';
config();

const PORT = process.env.PORT;
const NODE_ENV = process.env.NODE_ENV;
const HOST = process.env.HOST;

const DB_HOST = process.env.DB_HOST;
const DB_PORT = process.env.DB_PORT;
const DB_USERNAME = process.env.DB_USERNAME;
const DB_PASSWORD = process.env.DB_PASSWORD;
const DB_DATABASE = process.env.DB_DATABASE;
const DB_DIALECT = process.env.DB_DIALECT;

const ACCESS_TOKEN_SECRET_KEY = process.env.ACCESS_TOKEN_SECRET_KEY;
const REFRESH_TOKEN_SECRET_KEY = process.env.REFRESH_TOKEN_SECRET_KEY;
const ACCESS_TOKEN_MAX_AGE = process.env.ACCESS_TOKEN_MAX_AGE;
const REFRESH_TOKEN_MAX_AGE = process.env.ACCESS_TOKEN_MAX_AGE;
const COOKIE_MAX_AGE = process.env.COOKIE_MAX_AGE;
const CORS_DOMAIN = process.env.CORS_DOMAIN;

const CLOUIDINARY_NAME = process.env.CLOUIDINARY_NAME;
const CLOUIDINARY_KEY = process.env.CLOUIDINARY_KEY;
const CLOUIDINARY_SECRET = process.env.CLOUIDINARY_SECRET;

const HOST_MAILER = process.env.HOST_MAILER;
const PORT_MAILER = process.env.PORT_MAILER;
const USER_MAILER = process.env.USER_MAILER;
const PASS_MAILER = process.env.PASS_MAILER;

export {
	PORT,
	NODE_ENV,
	HOST,
	DB_HOST,
	DB_PORT,
	DB_USERNAME,
	DB_PASSWORD,
	DB_DATABASE,
	DB_DIALECT,
	ACCESS_TOKEN_SECRET_KEY,
	REFRESH_TOKEN_SECRET_KEY,
	ACCESS_TOKEN_MAX_AGE,
	REFRESH_TOKEN_MAX_AGE,
	COOKIE_MAX_AGE,
	CORS_DOMAIN,
	CLOUIDINARY_NAME,
	CLOUIDINARY_KEY,
	CLOUIDINARY_SECRET,
	HOST_MAILER,
	PORT_MAILER,
	USER_MAILER,
	PASS_MAILER,
};
